# Generated by Django 4.1 on 2022-08-29 12:03

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('days_renaming', models.IntegerField(validators=[utils.validators.validate_renaming_days])),
            ],
        ),
    ]
