# Generated by Django 4.1 on 2022-08-30 06:35

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathoncounter',
            name='days_renaming',
            field=models.PositiveSmallIntegerField(default=0, validators=[utils.validators.validate_renaming_days]),
        ),
    ]
