# Generated by Django 4.1 on 2022-08-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_hackathoncounter_days_renaming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathoncounter',
            old_name='days_renaming',
            new_name='days_remaining',
        ),
    ]
